### ISSUE TITLE
[Feature request] Skip backlog

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#100]
I think it would be really helpful to have a per-run (not permanent) option to skip backlog when running. For example, if I want to update MS really quick, and I haven't played any music since closing it, I may want to skip scrobbling backlog if there is none to be scrobbled, to prevent potential double scrobbles. Something like `--skip-backlog` would be cool.

**Comment by FoxxMD** [comment]
When and between what services are you experiencing double scrobbles? I would prefer to fix the root of the problem.

> and I haven't played any music since closing it

MS works best when it is left always-on. Is there a reason you are stopping it instead of running it as a [background service?](https://foxxmd.github.io/multi-scrobbler/docs/installation/service)

**Comment by duckfromdiscord** [comment]
> When and between what services are you experiencing double scrobbles? I would prefer to fix the root of the problem.
Between MS and maloja. Some but not all of the songs are re-scrobbled 15 or so minutes later.

> MS works best when it is left always-on. Is there a reason you are stopping it instead of running it as a background service?
Updating it or after a crash

**Comment by duckfromdiscord** [comment]
> All tracks? From all sources? I need more information, and logs would help.

My only source is Spotify and it's not all tracks. Some of them don't double scrobble. Perhaps it's an issue with time zones or my system clock. The doubly-scrobbled songs usually have timestamps up to 15 minutes after the old scrobble at the correct time.

> After MS crashes? Or your machine? What is causing MS to crash? Are there logs?

The latest MS crash belongs in its own issue (waiting for it to happen again so I can collect logs), but my main idea was to skip backlog after updating :)

**Comment by FoxxMD** [comment]
Disabling backlog scrobbling is now available in [0.6.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.0) (on flathub now as well).

Assuming you have a [`spotify.json`](https://json-schema.app/view/%23/%23%2Fdefinitions%2FSpotifySourceConfig/%23%2Fdefinitions%2FCommonSourceOptions?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fmaster%2Fsrc%2Fbackend%2Fcommon%2Fschema%2Fsource.json) config you'd use it like:

```json
{
  ...
  "data": { ... }
  "options": {
   "scrobbleBacklog": false
  }
}

0.6.0 brings a lot of improvements to duplicate detection though so you may not need to disable backlog at all.

**Comment by duckfromdiscord** [comment]
This is awesome! Is there a way to do it per-run as a command line argument?

**Comment by FoxxMD** [comment]
There is not. MS has a slightly contrived startup process which would require a bit of work to support cli args. I've also designed to be long-running and don't plan to support a use-case where it is started frequently as a one-off.

I'd also still rather address the root issue. If you are still having duplicate scrobble problems please try to reproduce it and provide as much logs/details as possible in a new issue.
