### ISSUE TITLE
Songs that are part of compilations do not get scrobbled from Plex

### ISSUE THREAD

**Issue by alexandrutirdea** [FoxxMD/multi-scrobbler#104]
Hello,

While testing the Docker version of this software, I noticed that songs that are part of compilations are rejected by last.fm due to multi-scrobbler picking up "Various Artists" as the artist. Last.fm accepts album artist as a tag, and that would fix it easily if the scrobbles could contain both artist and album artist tags, but I don't know if Plex makes that tag available to third party applications. Their own scrobbling plugin, which I would love to ditch, sends accurate scrobbles containing both tags.

**Comment by FoxxMD** [comment]
@alexandrutirdea you can test a fix for this on docker [`foxxmd/multi-scrobbler:develop`](https://hub.docker.com/layers/foxxmd/multi-scrobbler/develop/images/sha256-5a386254d05dd327e21ffd42e70ab5cc7c8aaa473181a0c6a7e593fc0b9c6041?context=explore)

**Comment by FoxxMD** [comment]
This should now be fixed in [0.6.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.2)
