### ISSUE TITLE
Webscrobbler Connector List

### ISSUE THREAD

**Issue by undaunt** [FoxxMD/multi-scrobbler#112]
**Describe the bug**
It seems unclear where the list of connectors to define for the webscrobbler whitelist/blacklist lives. Is this provided by external documentation? If so, 

**Expected behavior**
Whitelist/blacklist connector types are provided as part of the web scrobbler documentation, or linked to externally.

**Comment by FoxxMD** [comment]
[Fixed in 0.6.3](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.3) with docs [here](https://foxxmd.github.io/multi-scrobbler/docs/configuration#connectors-blackwhitelist)
