### ISSUE TITLE
multi-scrobbler documentation issue

### ISSUE THREAD

**Issue by falcie1337** [FoxxMD/multi-scrobbler#119]
**Describe the bug**
When you open multi-scrobbler, it prompts you for an unexisting GitHub doc on how to make it run as a background service, making it hard to know how to actually do it (it is very annoying to have a terminal open all the time just for being able to scrobble your music) 

**To Reproduce**
1. Run multi-scrobbler
2. Click on 'https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/service.md'
3. See 404 page

**Expected behavior**
An actual markdown page documenting on how to make multi-scrobbler run as a background service.

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: [e.g. 0.6.2 on flatpak]

Hope this gets done with quickly since it is a really useful app, but having two terminals open when i want to scrobble is really annoying and having it run on the background would be much more convenient, don't really know why the .md file just got deleted from the source code but yeah, just pointing it out.

**Comment by FoxxMD** [comment]
https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/installation/service.md

**Comment by falcie1337** [comment]
> https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/installation/service.md or https://foxxmd.github.io/multi-scrobbler/docs/installation/service

Very much appreciated! :)
