### ISSUE TITLE
configuration.md links to explore schema are broken

### ISSUE THREAD

**Issue by Bujiraso** [FoxxMD/multi-scrobbler#122]
In [docsite/docs/configuration/configuration.md](https://github.com/FoxxMD/multi-scrobbler/blob/af037ee215ab5e2f3d28e0dd29583b13cf7a4192/docsite/docs/configuration/configuration.md?plain=1#L84), the following link is given:

https://json-schema.app/view/%23/%23%2Fdefinitions%2FLastfmSourceConfig?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fdevelop%2Fsrc%2Fcommon%2Fschema%2Fsource.json

However navigating to it shows an error:
![image](https://github.com/FoxxMD/multi-scrobbler/assets/1975771/435f5365-ce49-47fe-8809-670de7a50c89)

```
Schema load failed

Attempted to pull the JSON Schema down from the public internet.

Error: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data
```

It looks like the `backend` folder is missing from this

**Comment by FoxxMD** [comment]
[Fixed in 0.6.3](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.3)
