### ISSUE TITLE
BASE_URL Ignoring Path Params

### ISSUE THREAD

**Issue by OpenSrcerer** [FoxxMD/multi-scrobbler#125]
Hello.

**Describe the bug**
I am using multi-scrobbler for the first time ever, running it in Docker. I am running many other services under the same hostname and as such I use paths to discern every service with NGINX fronting everything. As such, I also configured multi-scrobbler to perform a similar task.

However, I notice that the `/scrobbler/` part of the URI is not being properly used in the base URL. 

![image](https://github.com/FoxxMD/multi-scrobbler/assets/46500918/e62a7378-202d-4d8a-bb61-5977f0ed66ce)

If I manually call `/scrobbler/lastfm/callback` just to test, I get redirected to `https://my.domain.com/` instead of the actual base URL provided.

**Expected Behavior**
I expect that given a base URL, the path part should also be included.

**docker-compose** (snippet)
```
multi-scrobbler:
    image: foxxmd/multi-scrobbler
    environment:
      - BASE_URL=https://my.domain.com/scrobbler/
```

**Nginx Config:**
```
location /scrobbler/ {
        proxy_set_header X-Forwarded-Host     $host;
        proxy_cookie_path / "/; Secure";
        proxy_pass                            http://localhost:4043/;
        proxy_redirect                        http:// https://;
}
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: currently latest tag on Docker

**Comment by FoxxMD** [comment]
I've got this working, tentatively, using the image [`foxxmd/multi-scrobbler:baseurl`](https://hub.docker.com/layers/foxxmd/multi-scrobbler/baseurl/images/sha256-d1fcaca4490f4c035f9737b866ad417b0d83569ffcf3039d796ad290c8be0cfb?context=repo). I haven't tested it thoroughly , CRA made me jump through some hoops I don't particularly like, and there's a breaking-change in the URL structure so I won't be merging this into a release any time soon. Let me know if the image work for you and any issues you come across.

**Comment by OpenSrcerer** [comment]
Hi! Thanks for your quick assistance. It seems that your new image fixed the main problem, but unfortunately I am still having some other issues.

1) **It appears that the URL fix did not work for the callback URL for last.fm.** I still get a 307 which redirects me to /api/lastfm/callback for some reason. I'm not sure if this breaks anything but I think it's still important to report.

2) **I'm having trouble with the configuration.** I'm getting a `[Scrobblers] [Config] Schema Error` with no further info. Yes, I did check the schema you have mentioned in your docs, but it appears that it is not working:

![image](https://github.com/FoxxMD/multi-scrobbler/assets/46500918/454508b6-2b16-4845-a93b-3e4f864854ee)

I did try some other variations of the config as per your docs but I wasn't able to get this working. Here is the configuration I am using:
"sources": [
    {
      "name": "listenbrainz",
      "configureAs": "source",
      "clients": ["last.fm"],
      "data": {
        "token": "my-token",
        "username": "my-username"
      }
    }
  ],
  "clients": [
    {
      "name": "last.fm",
      "configureAs": "client",
      "data": {
        "apiKey": "my-api-key",
        "secret": "my-secret",
        "redirectUri": "https://music.danielstefani.online/scrobbler/lastfm/callback"
      }
    }
  ],
  "webhooks": []

Feel free to connect to the instance [here](https://music.danielstefani.online/scrobbler/) if you want to check it out for yourself.

**Comment by FoxxMD** [comment]
> Feel free to connect to the instance here

I may not explicitly lay it out in the docs but MS was not designed or intended to be exposed publicly. Unless you're using a [WebScrobbler source](https://foxxmd.github.io/multi-scrobbler/docs/configuration#webscrobbler) there's no reason for it be accessible outside of your LAN. (This is also a factor in why reverse proxy hasn't been an issue until now...its not really supposed to be used in this way.)

> schema not working

This was [fixed](https://github.com/FoxxMD/multi-scrobbler/issues/122) in the develop branch and just [released today](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.6.3). Schema links in the docs should work for you now.

> `[Scrobblers] [Config] Schema Error`

I haven't checked but I have a hunch it may be the client name. Try changing `last.fm` to `lastfm` and see if that fixes anything.

**Comment by OpenSrcerer** [comment]
Thank you very much @FoxxMD! I've got it to work perfectly the way I wanted it to work at the moment. I appreciate you for making this awesome tool.

> MS was not designed or intended to be exposed publicly

Yeah, I understand that now, appreciate the explanation. The only thing I'll need to view is the logs anyway - and you can do that easily with Docker. The only concern that I had was the callback URL for `last.fm`, but it doesn't seem to be an issue.

>  Schema links in the docs should work for you now.

Awesome! The problem was the missing "type" attribute in the client and source.

IMHO this is working great right now, my issue is resolved.
