### ISSUE TITLE
Explore changing base docker distro

### ISSUE THREAD

**Issue by FoxxMD** [FoxxMD/multi-scrobbler#126]
Multiple issues in the past caused by DNS problems are directly related to using alpine with `musl`. The upcoming chromecast source also has issues with this due to musl's non-support for mDNS resolution.

LSIO has other base images that are almost as small as alpine. It's worth investigating if debian/ubuntu bases will have similar size and ease of installation as the current alpine base. Switching to one of these would mean back to glibc and saying goodbye to network/dns headaches.

**Comment by FoxxMD** [comment]
@Ardakilic If you'd like to test it out I now have a debian-based docker image available [`foxxmd/multi-scrobbler:develop-debian`](https://hub.docker.com/layers/foxxmd/multi-scrobbler/develop-debian/images/sha256-a0164280052b5c56b6d32e16244b9cd95ea9021d1fa68aab45dcd8fe8e7b3cd0?context=repo). It includes the fixes from 134.

**Comment by Ardakilic** [comment]
By simply altering the tag and modifying my ipv6 settings on host machine, here's my rough test:

* ipv6 disabled, on `:develop-debian` tag, it's working as intended. In about 15 mins, I only got 1 timeout in between, unlike like every 10 seconds, which is definitely a fluke.
* ipv6 enabled, on `:develop-debian` tag, it's working nicely. It about 15 minutes, no timeouts at all.

So I can say for my case, it's fixed for both the cases with the `:develop-debian` tag. 

@FoxxMD are you going to provide both flavors generated on pipeline, or are you going to stick move on to Debian based image?

**Comment by FoxxMD** [comment]
For now I'll be building both flavors with github actions. The non-suffixed tags will stay as alpine.

For the debian image I'm encountering a showstopping bug during `npm install` but _only for the arm64 arch._ This same error does not occur for the alpine arm64 build. Because of this error the build fails so there will be no arm64 arch versions of `*-debian` tags for now.

```
#17 139.5 npm verb audit error FetchError: request to https://registry.npmjs.org/-/npm/v1/security/audits/quick failed, reason: Client network socket disconnected before secure TLS connection was established
#17 139.5 npm verb audit error     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
#17 139.5 npm verb audit error     at ClientRequest.emit (node:events:517:28)
#17 139.5 npm verb audit error     at _destroy (node:_http_client:882:13)
#17 139.5 npm verb audit error     at onSocketNT (node:_http_client:902:5)
#17 139.5 npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
#17 139.5 npm verb audit error  FetchError: request to https://registry.npmjs.org/-/npm/v1/security/audits/quick failed, reason: Client network socket disconnected before secure TLS connection was established
#17 139.5 npm verb audit error     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
#17 139.5 npm verb audit error     at ClientRequest.emit (node:events:517:28)
#17 139.5 npm verb audit error     at _destroy (node:_http_client:882:13)
#17 139.5 npm verb audit error     at onSocketNT (node:_http_client:902:5)
#17 139.5 npm verb audit error     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
#17 139.5 npm verb audit error   code: 'ECONNRESET',
#17 139.5 npm verb audit error   path: null,
#17 139.5 npm verb audit error   host: 'registry.npmjs.org',
#17 139.5 npm verb audit error   port: 443,
#17 139.5 npm verb audit error   localAddress: null,
#17 139.5 npm verb audit error   errno: 'ECONNRESET',
#17 139.5 npm verb audit error   type: 'system'
#17 139.5 npm verb audit error }
```

The bug is reproducible when using [Github Actions](https://github.com/FoxxMD/multi-scrobbler/actions/runs/7745108736/job/21155855792) from the repo, running Github Actions locally with [act](https://github.com/nektos/act), and directly by trying to build the arm64 arch with [buildx](https://github.com/docker/buildx).

Reproducing with buildx:

```shell
git clone --branch develop https://github.com/FoxxMD/multi-scrobbler .
cd multi-scrobbler
docker buildx build -t msdebianarm --progress=plain -f debian.Dockerfile --platform=linux/arm64 --load .
```

All my attempted fixes are documented in [`debain.Dockerfile`](https://github.com/FoxxMD/multi-scrobbler/blob/develop/debian.Dockerfile). I've tried:

* Installing `ca-certificates` and `openssh-client` apt packages
* Verifying TLS compatibility with https://www.npmjs.com/package/tls-test (no problem)
* Disabling npm audits with `--no-audit`
* Using ubuntu base image variant

The only thing I haven't tried so far is replacing the nodesource.com node/npm install method with the [install method from the official docker-node dockerfile](https://github.com/nodejs/docker-node/blob/main/18/bookworm-slim/Dockerfile)

**Comment by Ardakilic** [comment]
@FoxxMD 🤔 

To test on arm64, could you please modify the installation line like this?

```bash
npm ci --maxsockets 1 --verbose
```

**Comment by FoxxMD** [comment]
Thanks for the suggestion but I'm getting the same result and the debug output is the same well.

**Comment by Ardakilic** [comment]
Toally weird! Usually this issue is being resolved by simply reducing the maxsockets value, however I did it and got the exact same result on exact same packages on debian/arm64 on my fork.

**Comment by FoxxMD** [comment]
Same result when using same method as official docker-node to install node/npm (direct binary from nodejs.com)

**Comment by FoxxMD** [comment]
@Ardakilic It seems upgrading the node version used in the debian docker image to the latest LTS (18 -> 20) fixed the timeout/connection issue :shrug: I've pushed an arm64 version of the debian tag. Will use this for awhile on `develop` to make sure its not a fluke before cutting a release for it.

**Comment by Ardakilic** [comment]
@FoxxMD Awesome news! I was almost positive it was a caching issue from GitHub's end.. Let me know if/when you need me to check the develop when it's ready!

**Comment by FoxxMD** [comment]
Closed with [0.7.0](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.7.0):

* debian build using node20 is published alongside default alpine build
* [docs have guidance](https://foxxmd.github.io/multi-scrobbler/docs/installation#network-issues) for using debian flavor in the event of network issues

**Comment by Ardakilic** [comment]
Awesome news! I'll try on my Debian flavour on my Debian host machine, using docker this evening!

**Comment by Ardakilic** [comment]
@FoxxMD Tried on `:latest-debian` tag. So far so good! 🚀  Tried scrobbling from last.fm (through Spotify) to Maloja, worked nicely. Currently hosting it on my private Linux Debian VPS, through docker-compose.

I'll check logs if something weird occurs. Let me know if you need any further test

**Comment by FoxxMD** [comment]
Hey @Ardakilic how has the debian build been working for you? Thinking of making debian the default build.

**Comment by Ardakilic** [comment]
Hello @FoxxMD , Zero issues so far! Happy Debian flavour (`:latest-debian`) user here 😊
