### ISSUE TITLE
[Question] Images

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#128]
How is album/track art handled in multi-scrobbler? Is it exposed to the scrobbling backends? I'm in the process of creating a PR to maloja that allows image data to be included alongside scrobble data, and I was considering creating a PR to multi-scrobbler that would include image data in scrobbles. But I need to know whether multi-scrobbler exposes direct URLs to images, or base64 encoded images.

**Comment by FoxxMD** [comment]
It doesn't currently do any kind of image handling.

**Comment by duckfromdiscord** [comment]
No problem then!
