### ISSUE TITLE
Randomly terminated

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#132]
Ever since the update, multi-scrobbler has been randomly terminating, likely due to high memory usage. The amount of memory I have on that machine hasn't changed, and I haven't installed anything new (in fact I uninstalled something that was running in the background that I suspected caused this). Could there be a new memory leak?

**Comment by FoxxMD** [comment]
Have you monitored memory usage and seen it increasing over time?

**Comment by duckfromdiscord** [comment]
I haven't seen it increase over time, but I did uninstall something that was taking a lot of memory. Should I run some sort of program that records memory usage?

**Comment by duckfromdiscord** [comment]
Closing this issue as it hasn't happened since I started my Docker container. Will reopen if it does.
