### ISSUE TITLE
Suddenly unable to authenticate with lastfm or spotify

### ISSUE THREAD

**Issue by HTangl** [FoxxMD/multi-scrobbler#149]
**Setup**
Running a docker container through docker desktop (4.28.0) on a windows 10 machine, using jellyfin and spotify as sources and lastfm as the client
- multi-scrobbler: v0.7.0
- jellyfin: 10.8.10

**Describe the bug**
Unable to scrobble tracks to lastfm from jellyfin or spotify due to failed authentication. When trying to authenticate the lastfm client or spotify source getting time out errors. Docker container was working normally for months then suddenly stopped scrobbling about a week ago. Tried updating the image and making a new container with all the same environment variables and was able to get everything working again for 2 days but then suddenly started experiencing the same issues and now have been unable to get lastfm and jellyfin working again. I have made no changes to my system and am at a loss as to why it stopped working in the first place or why I can't get lastfm to authenticate now. Local ip address has not changed, have tried changing several environment variables, removing spotify as a source, have recreated the container several times, created a new api application on lastfm several times, tried disabling all older lastfm api applications.

![image](https://github.com/FoxxMD/multi-scrobbler/assets/94026171/131c1d74-951e-4532-9dba-ca88c7210cdf)
![image](https://github.com/FoxxMD/multi-scrobbler/assets/94026171/39941169-4c73-4de6-b6ee-2ff87b20cdf1)
![image](https://github.com/FoxxMD/multi-scrobbler/assets/94026171/85232991-9b98-4f75-87b6-84ebd388167d)

**Comment by HTangl** [comment]
here are all my docker run variables I've been using
![image](https://github.com/FoxxMD/multi-scrobbler/assets/94026171/bf235801-17da-457a-b0da-d0de55f6f06f)

**Comment by FoxxMD** [comment]
Can you try to using the debian variant of the docker image to see if this [resolves your issues?](https://foxxmd.github.io/multi-scrobbler/docs/installation#network-issues) Try using `foxxmd/multi-scrobbler:latest-debian`

**Comment by HTangl** [comment]
Wow, it was in the documentation the whole time, I feel very dumb. Thank you so much for responding quickly, switching to the debian version resolved everything!
