### ISSUE TITLE
Feature: Jellyfin 10.7 API Integration

### ISSUE THREAD

**Issue by Extarys** [FoxxMD/multi-scrobbler#15]
The backend is similar to emby but I'm unsure how much the API might be different now.

If this is implemented I would refer to the 10.7 release of Jellyfin (docker image currently labeled as **stable-rc**).

**Comment by FoxxMD** [comment]
Their documentation seems lacking...most I've found is this [plugin page](https://jellyfin.org/docs/general/server/plugins/index.html) and a short [notifications page](https://jellyfin.org/docs/general/server/notifications.html). I haven't found any documentation on how emby's webhooks work either :shrug: 

Do you currently use Jellyfin? If you can find a way to post events to a URL (maybe with this [plugin?](https://github.com/crobibero/jellyfin-plugin-webhook)) and give me an example payload that would go along way towards getting this integrated. Otherwise this will be backburner while I get the other integrations with actual docs implemented first, and then only once i have time to install Jellyfin play around with it.

**Comment by Extarys** [comment]
@FoxxMD There is the [Plugin API documentation here](https://jellyfin.org/docs/plugin-api/index.html) in case you missed it (I discovered that page a few days ago actually).

Not sure how up-to-date this is but it's a start.

**Comment by FoxxMD** [comment]
Thanks but that API is for writing plugins for Jellyin (in C#), not for a web API.

**Comment by crobibero** [comment]
Currently the linked plugin does not send playback events, but it's on the radar

**Comment by FoxxMD** [comment]
@crobibero hey im glad to hear that! Please do let me know if/when you get it implemented.

**Comment by crobibero** [comment]
With version 2.2020.1217.1453 I've added playback notifications.
I still need to add some documentation, but it should have more then enough information to get scrobbling working to any destination

Sample with all of the possible fields from a PlaybackStop event. Note that there can be many more provider ids.
```json
{
  "Timestamp": "2020-12-17T07:49:48.2669524-07:00",
  "UtcTimestamp": "2020-12-17T14:49:48.2669577Z",
  "Name": "Ad Astra",
  "Overview": "Astronaut Roy McBride undertakes a mission across an unforgiving solar system to uncover the truth about his missing father and his doomed expedition that now, 30 years later, threatens the universe.",
  "ItemId": "97464e1e2f8c20f4ac620c4052358263",
  "ServerId": "2927b21e279b45b7aadbfb5a3775a573",
  "ServerUrl": "http://localhost:8096",
  "ServerName": "Jellyfin Server",
  "ItemType": "Movie",
  "Year": 2019,
  "Provider_imdb": "tt2935510",
  "PlaybackPositionTicks": 122443950,
  "MediaSourceId": "97464e1e2f8c20f4ac620c4052358263",
  "IsPaused": false,
  "IsAutomated": false,
  "DeviceId": "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84My4wfDE2MDc1ODA3MjQwMTk1",
  "DeviceName": "Firefox",
  "ClientName": "Jellyfin Web",
  "NotificationType": "PlaybackStop",
  "PlayedToCompletion": false,
  "Username": "Cody",
  "UserId": "4806a23444eb4f29b8ac01e8df4f79f5"
}
```

**Comment by FoxxMD** [comment]
@crobibero fantastic! Thanks for getting that implemented so fast. I will give jellyfin a try when rc2 is released and get this implement then. A few questions for you on the payload sample:

* Can you provide `duration` property so I can see the length (in some time unit) an item is?
* What unit is `PlaybackPositionTicks` measured in?
* Would it be possible to provide the jellyfin server version in the payload? Or is there another way I can get this info? That way I can check for compatibility on startup. If not that's ok I can just put reqs in documentation.

**Comment by crobibero** [comment]
Good points
I've added some additional properties:

```json
{
  "ServerId": "2927b21e279b45b7aadbfb5a3775a573",
  "ServerName": "Jellyfin Server",
  "ServerVersion": "10.7.0",
  "NotificationType": "PlaybackProgress",
  "Timestamp": "2020-12-18T08:47:13.1460515-07:00",
  "UtcTimestamp": "2020-12-18T15:47:13.1460567Z",
  "Name": "Ad Astra",
  "Overview": "Astronaut Roy McBride undertakes a mission across an unforgiving solar system to uncover the truth about his missing father and his doomed expedition that now, 30 years later, threatens the universe.",
  "ItemId": "97464e1e-2f8c-20f4-ac62-0c4052358263",
  "ServerUrl": "http://localhost:8096",
  "ItemType": "Movie",
  "RunTimeTicks": 73822535680,
  "RunTime": "02:03:02",
  "Year": 2019,
  "Provider_imdb": "tt2935510",
  "PlaybackPositionTicks": 377975200,
  "PlaybackPosition": "00:00:37",
  "MediaSourceId": "97464e1e2f8c20f4ac620c4052358263",
  "IsPaused": false,
  "IsAutomated": true,
  "DeviceId": "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODMuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84My4wfDE2MDc1ODA3MjQwMTk1",
  "DeviceName": "Firefox",
  "ClientName": "Jellyfin Web",
  "Username": "Cody",
  "UserId": "4806a234-44eb-4f29-b8ac-01e8df4f79f5"
}
```

**Comment by FoxxMD** [comment]
@crobibero excellent thank you! duration and run time help tremendously to ensure i don't post duplicate scrobbles in the event the track is started/stopped multiple times. :+1:

**Comment by FoxxMD** [comment]
@crobibero jellyfin 10.7 finally released! :tada: Plugin works well (was almost unusable in RCs, they fixed a lot of things it seems) but I have a few more requests for, if I may be so bold...

Here's what I'm with seeing (plugin version `2.2021.304.228`) as a payload using the "Send All Properties" checkbox (awesome addition btw):

```js
{
  ServerId: '8829f5772fa2479387ef67d6620e6fcd',
  ServerName: 'Jellyfin Server',
  ServerVersion: '10.7.0',
  ServerUrl: '',
  NotificationType: 'PlaybackProgress',
  Timestamp: '2021-03-12T10:56:29.2578018-05:00',
  UtcTimestamp: '2021-03-12T15:56:29.2578084Z',
  Name: 'Please Help Me',
  Overview: '',
  ItemId: 'fca6d299daf89e1a59cf41ef99b515cd',
  ItemType: 'Audio',
  RunTimeTicks: 2894628608,
  Year: 2009,
  Provider_musicbrainzalbumartist: 'd4d16c2e-7e7f-4e80-a4c3-c82d08610e04',
  Provider_musicbrainzartist: 'd4d16c2e-7e7f-4e80-a4c3-c82d08610e04',
  Provider_musicbrainzalbum: '7fcb9ce2-2756-4a73-9a8c-19e52754ddd8',
  Provider_musicbrainzreleasegroup: '2d6161fa-77dd-415e-9681-857614e34d27',
  Provider_musicbrainztrack: 'd59f4d85-2704-3622-9b35-6512d7ae8816',
  PlaybackPositionTicks: 421005340,
  PlaybackPosition: '00:00:42',
  MediaSourceId: 'fca6d299daf89e1a59cf41ef99b515cd',
  IsPaused: false,
  IsAutomated: true,
  DeviceId: 'TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvODguMC40MzI0LjE4MiBTYWZhcmkvNTM3LjM2fDE2MTU1NjIzMjgzNzY1',
  DeviceName: 'Chrome',
  ClientName: 'Jellyfin Web',
  Username: 'foxxmd',
  UserId: 'e0af8e41c5c24f9297c1a5d22e39df85'
}
```

* the `duration` and `runtime` properties you mentioned earlier are not present! Is it possible to add these back in?
* I understand the base item properties are more geared towards tv/movies but if `artist` is something you can easily add in to the payload that would be awesome. I need _at least_ an `artist` property in order to properly record a track a play. Preferably also an `album` property. 

Thanks again for your work on getting a generic destination for this plugin!

**Comment by crobibero** [comment]
Not sure where the `RunTime` field went off to, so I've added it back.
Current output for music playback:
```json
{
  "ServerId": "c0edd29e086d4aa79017ea6055ef8568",
  "ServerName": "Jellyfin Server",
  "ServerVersion": "10.8.0",
  "ServerUrl": "",
  "NotificationType": "PlaybackProgress",
  "Timestamp": "2021-03-13T14:44:06.3946157-07:00",
  "UtcTimestamp": "2021-03-13T21:44:06.3946223Z",
  "Name": "Jesus H. Macy",
  "Overview": "",
  "ItemId": "3de8f34161e6c3df9ce6f094c3efee1d",
  "ItemType": "Audio",
  "RunTimeTicks": 2049866624,
  "RunTime": "00:03:24",
  "Year": 2013,
  "Album": "Acceptance Speech",
  "Artist": "Dance Gavin Dance",
  "Provider_musicbrainzalbumartist": "16456fed-c9f2-4adf-b6ea-97b648c474d2",
  "PlaybackPositionTicks": 300220,
  "PlaybackPosition": "00:00:00",
  "MediaSourceId": "3de8f34161e6c3df9ce6f094c3efee1d",
  "IsPaused": false,
  "IsAutomated": false,
  "DeviceId": "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84NS4wfDE2MTE5NzA1MjQ3OTA1",
  "DeviceName": "Firefox",
  "ClientName": "Jellyfin Web",
  "Username": "Cody",
  "UserId": "0ef60b2496e44cdaaabee438168ecac8"
}
```

**Comment by FoxxMD** [comment]
@crobibero thank you! <3

**Comment by FoxxMD** [comment]
@Extarys please try the `develop` branch or `develop` tag on dockerhub with [these instructions](https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/configuration.md#jellyfin) and let me know if you have any issues.
