### ISSUE TITLE
Scrobble existing listens? (navidrome to listenbrainz)

### ISSUE THREAD

**Issue by ryankupk** [FoxxMD/multi-scrobbler#166]
I have a navidrome server that I've been using for over year, and all of my listens have been scrobbled from different clients to the navidrome server. I started scrobbling to listenbrainz recently, and just do so with the native scrobbling in navidrome. I want to be able to scrobble all of my existing listens to listenbrainz as well, and I thought that *maybe* this project could do that as well but I haven't seen any information about this specific use case in any of the documentation. I spun up an instance (just built from source and created a config.json file) and it seems like it only scrobbles new listens. So my questions are:

1. Is this doable now and I missed something? 
2. Could this be implemented in the future if not?

**Comment by FoxxMD** [comment]
I'm not sure I understand what you are asking for. As far as I know Navidrome does not store scrobbles and the only "recent" history it does store is order albums of recently played albums.

Can you direct me to where you can find a list of recent listens?

**Comment by ryankupk** [comment]
I looked through that same list of subsonic API endpoints and couldn't find anything either. I mostly was going off the fact that feishin maintains a play count for albums when sorting by "Most Played", which I assumed was server-side data. I think this *could* just be cached locally, but it's also aligned with the "Most played albums" section in Symfonium on android. I thought this meant that it had to be stored somewhere server-side and queried by both clients because I don't think that I could have possibly listened to the same albums relatively frequently on my desktop and phone. Both also have a "Recently played" section, which could just be a stack of albums and *not* their counts, but I'm not sure. 

I might try to dig into feishin and see if I can find out where those listen counts are coming from. 

![image](https://github.com/user-attachments/assets/12d917a9-9169-4da6-abd0-fa9d5c2b80f4)

**Comment by FoxxMD** [comment]
Ok I see what you mean. The subsonic api defines a `playCount` property so this is what you are seeing here. Subsonic-compatible servers keep track of how many times you have played tracks off an album. Here's a screenshot of album data from my navidrome server

![image](https://github.com/user-attachments/assets/3e848847-5d24-4785-887a-f29a5d5eb55e)

Unfortunately, as far listening data goes, `playCount` is the **only** property that is stored. This property is also stored on tracks but regardless there is no "history" storing each time you listened to it (timestamp) or in what order. Without that information its not possible to reconstruct scrobbles in a way that would be meaningful to you.

The best that could be done is iterating your collection with the subsonic api and creating an artificial scrobble with some fixed time interval between each one. The scrobbles would also be created in an arbitrary order...I wouldn't recommend doing this for listenbrainz/last.fm as it would definitely mess up any recommendations they are providing but if you really wanted it could be done just to get the info into Maloja for safe-keeping.

**Comment by ryankupk** [comment]
Thanks for the deep dive, that all makes sense. I agree that it wouldn't be worth it, even if it is technically possible.
