### ISSUE TITLE
Is Deezer unusable now, due to not being able to create apps?

### ISSUE THREAD

**Issue by srfsh** [FoxxMD/multi-scrobbler#175]
For a while, it appears, Deezer does not allow users to create apps to utilize its API. As far I can tell, it's been half a year now according to the Reddit posts. As there seems to be no other way to use multi-scrobbler without the `accessToken`, which is derived through a dance performed with OAuth implementation of Deezer, this basically renders the Deezer-part of the app useless.

 Is there anything that can be done about this?

**Comment by FoxxMD** [comment]
I wasn't aware of this change, thanks for bringing it to my attention. 

I'm on vacation right now but will be able to look into this next week.

**Comment by srfsh** [comment]
As a workaround, people could connect Deezer to last.fm, and from there scrobble to other places.

**Comment by FoxxMD** [comment]
Unfortunately Deezer has pulled support for their API and creating new apps. While I can still use my existing app and auth does seem to work there is no guarantee this will continue to be the case. **What this means for multi-scrobbler:**

### Deezer integration will NOT be removed but a warning/deprecation will be logged

On MS startup a warning message will be logged noting the service has dropped API support and no functionality is guaranteed. **No support will offered for existing integrations going forward** as there really isn't anything I can do about it.

### Documentation will be updated to note deprecation, discourage use, and point to this issue

I will update documentation to note the current state of Deezer api support and point to this issue so users can discuss. It will also mention using last.fm as a workaround (thanks @srfsh )

### Open to future development

If Deezer decides to re-introduce their API in the future I am open to rewriting/re-enabled the integration for it.

If someone writes an unofficial wrapper for the Deezer website (like the youtube music wrapper) that scrapes the site for the same kind of functionality as the API I am also open to integrating that, assuming it is stable enough to use.

### UPDATE: New Deezer Source

**A new Deezer Source using ARL has been implemented and is now available in [v0.9.5](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.9.5)**. Setup and configuration is in the [docs](https://foxxmd.github.io/multi-scrobbler/docs/configuration/?deezerSource=arl#deezer).
___

* ["We're not accepting new application creation at this time. Please check again later."](https://developers.deezer.com/myapps) - My Apps page on developers.deezer.com
* ["Unfortunately the web SDK is not supported anymore and is not available anymore."](https://en.deezercommunity.com/features-feedback-44/apis-to-enable-3rd-party-apps-ndk-not-available-javascript-sdk-not-working-76108?postid=222090#post222090) - Deezer Staff at deezercommunity.com
* ["Api disabled...only available for existing access"](https://www.reddit.com/r/deezer/comments/1c2t7ly/comment/kztlpsp/) - Admin/Mod on r/deezer
* [Oauth may be broken for existing apps (gives `error 50`)](https://www.reddit.com/r/deezer/comments/1ddsd4y/comment/l90i5qv/)
* [Deezer support confirms api support no longer exists](https://www.reddit.com/r/deezer/comments/1bizi0k/comment/la96g6u/)

**Comment by srfsh** [comment]
Ah well, that's what you get with non-free services anyway :/

Appreciated for the explanation. I will be closing the issue, then.

**Comment by FoxxMD** [comment]
[A new Deezer Source using ARL has been released in 0.9.5](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.9.5)
