### ISSUE TITLE
Feature: scrobble modification based on artist/album

### ISSUE THREAD

**Issue by ComicMango** [FoxxMD/multi-scrobbler#185]
Context: I grew up with a variety of Asian music, but I received my formal education in English. Spotify automatically romanises or translates artist/album/song titles to English because (I presume) my operating system is in English. It's confusing especially when it's a translated title. I have asked for the option to display artist/album/song titles in their original language for years to no avail. Now that I'm running Multi-Scrobbler, I'll like to have more control over how my scrobbles are presented.

I have been using Multi-Scrobbler's scrobble modification to detect and rename artist/album/song titles to their original language, but I've run into a slight issue recently. I've renamed Dreams, an album by Elephant Gym, to its original title in Mandarin. I also have the album Dreams by The Whitest Boy Alive in my library, and now The Whitest Boy Alive has a Mandarin album in my library lol.

Is it possible to process the modification only if it's by a certain artist? In the same vein, process the modification for a certain song title only if it's by this artist/in this album. I'm not technically inclined enough to figure it out on my own, but I'm hoping I could add a condition between `postCompare` and `album` for instance:

        {
	        "sourceDefaults": {
		        "playTransform": {
			        "postCompare": {
				        "title": [
					        "/(\\s\\-\\s|\\s)(feat\\.(.+)|live|remastered(.+))$/i",
					        "/\\s\\-\\sRefine\\,the\\sconcert\\sLive$/i",
					        "/\\s\\-\\s滾石40\\s滾石撞樂隊\\s40團拚經典(.+)$/i"
				        ],
				        "album": [
					        "/\\s?\\(Remastered\\)$/i",
					        {
						        "search": "URA ARA BEST",
						        "replace": "ウラ嵐BEST"
					        },
					        {
						        "search": "Dreams",
						        "replace": "夢境"
					        }

Any help or pointers is greatly appreciated. Thanks in advance!

**Comment by ComicMango** [comment]
Thanks for getting back so quickly!

Oh, it totally is a niche functionality lol. I'm hoping it won't be too difficult or complex if you decide to implement it. Honestly just a weird personal hang-up.

If I could go on a tangent: I know that Multi-Scrobbler recognises some configuration file names by default i.e. spotify.json. I'm wondering if it will detect any json files in the config directory and parse them? For example, all my modifications for Elephant Gym in one config named `artist-elephantgym.json`. I don't have that many modifications yet, so they're still in one `config.json` at the moment.

Many thanks and I hope I'm not being too overbearing. Thanks!

P.S: Looks like a neat collection there! Elephant Gym is wonderful and they're a treat to watch live.

**Comment by FoxxMD** [comment]
@ComicMango please switch to using the docker image mentioned in #186 and [see this documentation comment.](https://github.com/FoxxMD/multi-scrobbler/pull/186#issuecomment-2341182187) I believe this should address your issue.

**Comment by FoxxMD** [comment]
@ComicMango have you had a chance to test this?

**Comment by ComicMango** [comment]
@FoxxMD Hi! Sorry, was on vacation just got back. I've tested both top-level and individual conditions and both work great. Thank you so much for your quick response!! My conditions for reference:

```
{
	"sourceDefaults": {
		"playTransform": {
			"postCompare": {
				"title": [
					"/(\\s\\-\\s|\\s)(feat\\.|live|remastered|life live)(.+)?$/i",
					"/\\s\\-\\sRefine\\,the\\sconcert\\sLive$/i",
					"/\\s\\-\\s滾石40\\s滾石撞樂隊\\s40團拚經典(.+)$/i"
				],
				"album": [
					"/\\s?\\(Remastered\\)$/i",
					{
						"search": "/滾石40\\s滾石撞樂隊\\s40團拚經典(.+)$/i",
						"replace": "滾石40 滾石撞樂隊 40團拚經典"
					},
					{
						"search": "Dreams",
						"replace": "夢境",
						"when": [
							{
								"artist": "Elephant Gym"
							}
						]
					}
				],
				"when": [
					{
						"artist": "Elephant Gym",
						"album": "Balance"
					}
				],
				"album": [
					{
						"search": "Balance",
						"replace": "平衡"
					}
				],
				"title": [
					{
						"search": "/Ocean in the Night(.+)$/i",
						"replace": "夜洋風景"
					},
					{
						"search": "Dance Together",
						"replace": "一起跳舞"
					},
					{
						"search": "Galaxy",
						"replace": "銀河"
					}
				]
			}
		}
	}
}
```

> If I could go on a tangent: I know that Multi-Scrobbler recognises some configuration file names by default i.e. spotify.json. I'm wondering if it will detect any json files in the config directory and parse them? For example, all my modifications for Elephant Gym in one config named `artist-elephantgym.json`. I don't have that many modifications yet, so they're still in one `config.json` at the moment.

And to answer my own question if there's anyone wondering, seems like MS only reads from `config.json`. Tried creating a separate json file to test top-level when conditions named `elephantGym_balance.json` then `config_elephantGym_balance.json` but MS couldn't detect them. The same conditions work fine in `config.json`.
