### ISSUE TITLE
Feature: Frontend

### ISSUE THREAD

**Issue by christophernewton** [FoxxMD/multi-scrobbler#19]
Hey there,

Thanks for creating this and supporting all the different scrobblers out there, your work is appreciated!

Im a front end dev and noticed the very basic views you have for the log/status area. If I were to create a frontend (still using ejs so that its still easily supported) would you be open to it?

What is there is functional and usable, just thought I could offer some help to make it look a little cleaner if you are open to it.

**Comment by FoxxMD** [comment]
Absolutely! A richer front end has been on my back burner list of ideas for awhile but I haven't had any incentive to build it because what's there works fine. Would love for you to take that on :)
