### ISSUE TITLE
Last.fm issue

### ISSUE THREAD

**Issue by christophernewton** [FoxxMD/multi-scrobbler#22]
Hey there FoxxMD

I just added last.fm as a client and started noticing an error with uts/date which was stopping it from scrobbling.

https://github.com/FoxxMD/multi-scrobbler/blob/master/clients/LastfmScrobbler.js#L56

```
TypeError: Cannot read property 'uts' of undefined
    at Function.formatPlayObj (file://CWD/clients/LastfmScrobbler.js:57:22)
    at file://CWD/clients/LastfmScrobbler.js:169:66
    at Array.map (<anonymous>)
    at LastfmScrobbler.refreshScrobbles (file://CWD/clients/LastfmScrobbler.js:169:41)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ScrobbleClients.scrobble (file://CWD/clients/ScrobbleClients.js:242:25)
    at async SubsonicSource.doPolling (file://CWD/sources/AbstractSource.js:140:40)
    at async SubsonicSource.startPolling (file://CWD/sources/AbstractSource.js:57:17)
    at async SubsonicSource.poll (file://CWD/sources/AbstractSource.js:40:9)
```

After looking around in the LastfmScrobbler file I could see that the destructure happening at the top of the file doesnt contain 

```
  date: {
      uts: time,
  },
```

Which seems to cause it to throw an error. I started to mess around with this but wanted to check in with you if you knew about this or if it is a setting/api that I havent set up correctly

The object being returned currently is 

```
{
  artist: {
    mbid: '0fb7d725-4dfd-45d2-944c-6ffa375a142d',
    '#text': 'And So I Watch You From Afar'
  },
  '@attr': { nowplaying: 'true' },
  mbid: '3541c2c9-3b93-4ecf-b359-607de96ae610',
  album: {
    mbid: 'a219c4d9-c56e-47d1-aa35-f34dbb2eb631',
    '#text': 'The Endless Shimmering'
  },
  streamable: '0',
  url: 'https://www.last.fm/music/And+So+I+Watch+You+From+Afar/_/Dying+Giants',
  name: 'Dying Giants',
  image: [
    {
      size: 'small',
      '#text': 'https://lastfm.freetls.fastly.net/i/u/34s/e7ae87a15f9f64aba56cc2709a6fb8f8.jpg'
    },
    {
      size: 'medium',
      '#text': 'https://lastfm.freetls.fastly.net/i/u/64s/e7ae87a15f9f64aba56cc2709a6fb8f8.jpg'
    },
    {
      size: 'large',
      '#text': 'https://lastfm.freetls.fastly.net/i/u/174s/e7ae87a15f9f64aba56cc2709a6fb8f8.jpg'
    },
    {
      size: 'extralarge',
      '#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/e7ae87a15f9f64aba56cc2709a6fb8f8.jpg'
    }
  ]
}
```

Thanks

**Comment by FoxxMD** [comment]
Hey @christophernewton thanks for investigating this! I believe the response does not include a timestamp because it is "now playing". I've added a fix that ignores any tracks from last.fm with `nowplaying` attribute or missing timestamp (since I can't use them anyway!) and logs the action if you have `debug` set as your log level.

Let me know if this fixes your issue. It's in the `develop` branch right now and the `develop` dockerhub tag.

Also -- please let me know if you are experiencing any issues using subsonic as a source. I've got something halfway implemented to improve scrobbling with it and any feedback you may have could help. Thanks!

**Comment by christophernewton** [comment]
@FoxxMD Looks like that sorted it out, cheers! Can see the tracks coming up in last.fm now and no errors are being thrown.

`please let me know if you experience any issues using subsonic as a source`: So far this app is the best solution Ive found to support the subsonic api (I'm about to uninstall the web-scrobbler now that this covers all my use cases). Will let you know if I catch any issues!
