### ISSUE TITLE
bug: Immense amount of logs

### ISSUE THREAD

**Issue by circle3451** [FoxxMD/multi-scrobbler#243]
### Please check existing knowledge before opening an issue

- [X] I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
- [X] I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)

### Describe the Bug

Hi
This day i noticed my server was stumbling on the backup of the MS logs directory. It seems that there is an enormous amount of files within it. I am as of right now `rm -r`-ing the directory and i can see the size slowly shrinking.

from
`3883405 Dec 18 23:02 logs`
to
`3409932 Dec 18 23:06 logs`

When restarting the removal inbetween checking that the size is actually going down i got these errors:

`rm: cannot remove '/multi-scrobbler/config/logs/scrobble-2024-10-26.648568.log': No such file or directory
rm: cannot remove '/multi-scrobbler/config/logs/scrobble-2024-10-26.648514.log': No such file or directory
rm: cannot remove '/multi-scrobbler/config/logs/scrobble-2024-10-26.648966.log': No such file or directory`
x1000's

My config is as follows:
`{
  "debugMode": false,
  "disableWeb": false,
  "logging": 
    {
      "file": false
    },
  "sourceDefaults": {
    "maxPollRetries": 1,
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5,
    "scrobbleThresholds": {
      "duration": 30,
      "percent": 30
    },
    "options": {
      "logPayload": false,
      "logFilterFailure": "warn",
      "logPlayerState": false
    }
  },
  "clientDefaults": {
    "maxRequestRetries": 1,
    "retryMultiplier": 1.5
  }
}`

### Platform

Docker

### Versions

- Multi Scrobbler 0.8.8
- Plex:latest
- Maloja: 3.2.2

### Logs

```shell
Cant acces the logs directory because my computer freezes
```

**Comment by FoxxMD** [comment]
This was due to a bug in the underlying logging library related to how daylight savings time was handled (first reported [here](https://github.com/FoxxMD/multi-scrobbler/issues/214), and another user affected [here](https://github.com/FoxxMD/multi-scrobbler/issues/234)). It affected European users first (DST on Oct 26) and was fixed in 0.8.7 before American DST.

The bug is fixed at this time and you can safely delete all the log files. Sorry for the inconvenience it caused!
