### ISSUE TITLE
Feature: Add support scrobbling for Media Center (Jriver)

### ISSUE THREAD

**Issue by etniasuns** [FoxxMD/multi-scrobbler#26]

**Comment by FoxxMD** [comment]
https://wiki.jriver.com/index.php/DevZone
https://wiki.jriver.com/index.php/Web_Service_Interface

I'll see what I can do about getting jriver setup (im on ubuntu) when I have some free time

**Comment by FoxxMD** [comment]
@etniasuns JRiver is available in the `develop` branch or docker image tag. [Docs here](https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/configuration.md#jriver)

**Comment by FoxxMD** [comment]
Available in [v0.4.3](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.3):

* `master` git branch
* `latest` docker image tag
