### ISSUE TITLE
Feature: Youtube / Youtube music

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/multi-scrobbler#34]
Would love to see Youtube and/or Youtube music integration.

**Comment by OmgImAlexis** [comment]
Okay that'll be good enough for now. At least with the chrome extension I can get `music.youtube.com` tracks scrobbled.

**Comment by FoxxMD** [comment]
Revisting this...it might be doable with ytmusicapi now.

* Setup is straight forward and [uses info that can be passed as a string](https://ytmusicapi.readthedocs.io/en/stable/setup.html)
* There is a [library history call now](https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_history)
* May be able to use [PyNode](https://github.com/fridgerator/PyNode) to interop between the two without too much friction?

**Comment by FoxxMD** [comment]
@OmgImAlexis if you'd like to give it a try its available on `foxxmd/multi-scrobbler:develop` image. [Config instructions here](https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/configuration.md#youtube-music)

**Comment by FoxxMD** [comment]
Implemented in [v0.4.1](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.1)
