### ISSUE TITLE
maloja 3.0.2 connection problem

### ISSUE THREAD

**Issue by cpuks** [FoxxMD/multi-scrobbler#42]
Hello, after recent maloja upgrade to 3.0.2 I see error:
```
2022-04-13T20:18:05+02:00 error : [Scrobblers ] TypeError: Cannot read property 'reduce' of undefined
at Function.formatPlayObj (file://CWD/clients/MalojaScrobbler.js:42:37) at file://CWD/clients/MalojaScrobbler.js:257:66 at Array.map () at MalojaScrobbler.refreshScrobbles (file://CWD/clients/MalojaScrobbler.js:257:41) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async ScrobbleClients.scrobble (file://CWD/clients/ScrobbleClients.js:300:21) at async SpotifySource.doPolling (file://CWD/sources/AbstractSource.js:168:38) at async SpotifySource.startPolling (file://CWD/sources/AbstractSource.js:78:17) at async SpotifySource.poll (file://CWD/sources/SpotifySource.js:252:9) 2022-04-13T20:18:05+02:00 error : [Scrobblers ] Encountered error while refreshing scrobbles for Maloja
```

**Comment by FoxxMD** [comment]
Hi! I have not had time to test MS with the new maloja version yet but I will get to it soon! Thanks for reporting this.

**Comment by FoxxMD** [comment]
Should be fixed in 8219dcecd74f0cfc6e7f8f22d33c5373d1db1010 ...testing now with docker image to verify before pushing to `latest` tag

**Comment by Eyeball753** [comment]
> Should be fixed in [8219dce](https://github.com/FoxxMD/multi-scrobbler/commit/8219dcecd74f0cfc6e7f8f22d33c5373d1db1010)
> 
> @cpuks please test the `latest` tag and verify its fixed for you, thanks!

I had the same issue as cpuks so I updated multi-scrobbler but saw that there was another Maloja update so I updated that to 3.0.3 and that's giving me a different error now.

Here is a log with the errors.
[multi-scrobbler-2022-04-15T04-02-06.log](https://github.com/FoxxMD/multi-scrobbler/files/8493735/multi-scrobbler-2022-04-15T04-02-06.log)

**Comment by FoxxMD** [comment]
@Eyeball753 can you try the `develop` docker image tag and let me know if that fixes things?

**Comment by Eyeball753** [comment]
Here's a log and image (to verify to you I'm using the develop tag) of me trying it with Maloja 3.0.2 and 3.0.3. Everything seems to work fine. Thank you!

[multi-scrobbler-2022-04-15T15-14-28.log](https://github.com/FoxxMD/multi-scrobbler/files/8496676/multi-scrobbler-2022-04-15T15-14-28.log)

![image](https://user-images.githubusercontent.com/63377657/163588375-93a54d18-cec8-44b8-bfb9-3d8c5016bbf2.png)

**Comment by FoxxMD** [comment]
@krateng Just FYI maloja 3.0.3 was returning a 500 with the old data shape (that I've been using since I created MS) for `newscrobble` endpoint :

```json
{
  "title": "string",
  "album": "string",
  "key": "string",
  "time": 1234567890,
  "artist": "Artist One / Artist Two",
  "seconds": 100
}
```

I changed `artist seconds` to `artists `length` and it fixed things.

```json
{
  "title": "string",
  "album": "string",
  "key": "string",
  "time": 1234567890,
  "artist": ["Artist One", "Artist Two"],
  "length": 100
}
```

Not sure which one was the issue. Just letting you know in case there was an actual BC for `newscrobble` since that would affect more than just MS.

**Comment by krateng** [comment]
`length` was actually the correct key before, `seconds` wouldn't have actually registered - it's just that Maloja before didn't complain about extra keys. I could implemented `seconds` as an alias or implement a more graceful fail on extra keys. `artist` and `artists` should both work (though `artists` is encouraged).

**Comment by cpuks** [comment]
@FoxxMD used develop and maloja 3.0.3 - works fine

**Comment by FoxxMD** [comment]
Oops! Didn't know seconds was wrong. I'll correct that. 

> I think your seconds value refers to the scrobble duration?

Nope, intention was always length of the track. So I had the right data just the wrong key :)
