### ISSUE TITLE
ARM docker image builds

### ISSUE THREAD

**Issue by northys** [FoxxMD/multi-scrobbler#45]
Are you interested in ARM builds? I've implemented those for maloja and it looks like you have almost the same actions file so it should be piece of cake to implement it into your workflow as well.

**Comment by FoxxMD** [comment]
Yes! If you can implement that and create a PR I would be happy to accept it.

**Comment by northys** [comment]
closing as it wasn't closed automatically in merge request. maybe [fixes #] must be used instead of [closes #]
