### ISSUE TITLE
BUG: Cannot authenticate Last.FM as Server

### ISSUE THREAD

**Issue by timkicker** [FoxxMD/multi-scrobbler#52]
Using the latest Version. How did it happen:
I set up my configuration file like the following:
![image](https://user-images.githubusercontent.com/33966128/192826547-cab9269b-1a9e-4820-bc15-0dd4afc045eb.png)

So far everything seems to work:
![image](https://user-images.githubusercontent.com/33966128/192826726-64a296cf-9425-47b9-834c-e16d0dddfdf8.png)

But after i hit the authentication-button (lastfm authentification window), an error gets thrown:
![image](https://user-images.githubusercontent.com/33966128/192827321-9a40f450-1c36-4703-8d2f-89d73df6c44e.png)

**Comment by FoxxMD** [comment]
Please change the lastfm redirect uri to `http://10.0.0.52:9078/lastfm/callback` and try again

**Comment by FoxxMD** [comment]
If this doesn't fix your issue please let me know and I can re-open.

**Comment by timkicker** [comment]
Sorry for the late answer. Thank you for your help but this sadly did not solve my issue.

![maloja_log](https://github.com/FoxxMD/multi-scrobbler/assets/33966128/cfd60ce4-5658-4fa7-978c-2796337ed25b)


Although the auth-screen tells me that everything worked?

![maloja_auth](https://github.com/FoxxMD/multi-scrobbler/assets/33966128/a7249490-8c1e-4936-88e2-547552fb7e91)
