### ISSUE TITLE
Access dashboard on server

### ISSUE THREAD

**Issue by all64bits** [FoxxMD/multi-scrobbler#53]
I have the docker image installed on my headless server (via docker-compose). I can't reach the dashboard when I try to remotely access http://servername:9078 (rather than http://localhost:9078). I've tried looking through the docs for a setting to allow for reaching the dashboard from another machine, but I can't find anything?

**Comment by FoxxMD** [comment]
Make sure you are [mapping the port](https://docs.docker.com/compose/compose-file/compose-file-v3/#ports) (9078) in the docker-compose.yml file

**Comment by all64bits** [comment]
Thanks @FoxxMD, I've mapped the port as 9078:9078 now. However when I go to http://servername:9078 I get a page saying 'Cannot GET /'?

**Comment by FoxxMD** [comment]
Have you checked to make sure the MS container is running? Do you have log output from it?

MS does not care (or know) where you are access it from as long as the container port is mapped. If you are sure the container is running then this sounds like a networking issue with your headless server. Does it have a firewall? Are you sure 9078 is open on the headless server?

**Comment by all64bits** [comment]
Thanks for the follow-up @FoxxMD. 

I've just tried the server/port now, and I can access the dashboard. I'm not sure what's changed between the time I checked when posting my last comment and now (nothing I'm aware of).

If I realize what change might've been causing the previous behavior, I can potentially open another issue, but will close this one now.

Thanks for the assistance!
