### ISSUE TITLE
Tracks showing up in multi-scrobbler, but not Maloja

### ISSUE THREAD

**Issue by crosbyh** [FoxxMD/multi-scrobbler#6]
I have multi-scrobbler set up to pull info in from Plex (via Tautulli) and Spotify. I have Maloja set up via API using ENV variables.

I am running in both applications in Docker. using multi-scrobbler:develop.

When multi-scrobbler starts up, the logs show:

```
2020-11-25T14:00:23-08:00 info   : [Scrobblers] Maloja client initialized
2020-11-25T14:00:23-08:00 info   : [Maloja    ] Test connection succeeded!
2020-11-25T14:00:23-08:00 info   : [Maloja    ] Maloja Server Version: 2.10.5
```

And when I play tracks in Spotify and Plex, they show up in the multi-scrobbler logs. However, the tracks never appear in Maloja. Am I missing a step?

**Comment by FoxxMD** [comment]
Do you see a scrobble confirmation in the log for Maloja? It should look like this once the app completes an api call to Maloja for a track scrobble:

```

2020-11-25T15:28:23-05:00 info   : [Maloja    ] Scrobbled (New)     => (Spotify) Jeff Parker - Blackman, played at 2020-11-25T15:27:48-05:00
2020-11-25T15:28:23-05:00 info   : [Spotify   ] New Track => Jeff Parker - Blackman, played at 2020-11-25T15:27:48-05:00
```

**Comment by FoxxMD** [comment]
Just deployed a change that may fix this as well...please try updating your container :) latest or develop

**Comment by crosbyh** [comment]
I updated my container on develop and it doesn't seem to have fixed the issue. I also updated my Maloja HOST setting because I noticed it was still set for IPV6. Set Maloja HOST=0.0.0.0 but that did not seem to fix the issue either. Still seeing a message on startup of multi-scrobbler that suggests successful connection to Maloja, but nothing shows up in Maloja.

I am not seeing scrobble confirmations in my multi-scrobbler log.

I do not seem to have an apis.log in my maloja/logs folder. Could that be indicative of a problem w/ Maloja install? I'm running a pretty standard setup of the container.

Here is the content of maloja/logs/debug.log:

```
2020/11/25 20:59:07  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 20:59:07  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 21:00:05  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 21:00:05  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 21:42:43  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 21:42:43  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 22:00:05  Query Cache: 0 Perm Hits, 5 Tmp Hits, 49 Misses; Current Size: 44/5
2020/11/25 22:00:05  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 10 Misses; Current Size: 0/10
2020/11/25 22:21:14  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 22:21:14  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 22:52:32  Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
2020/11/25 22:52:32  Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
```

**Comment by FoxxMD** [comment]
Thanks for the info. Your maloja instance is fine, `Test connection succeeded!` from your first log means its working. It's definitely an issue with this app :) I have been writing code under the assumption of an existing history in Maloja because that's how mine looks...so I'm running into use-cases now that break things when Maloja has zero history. Sorry! I will do more testing tomorrow with a clean Maloja install and no history to make sure I've caught everything.

But in the mean time I have push another change to `develop` that may fix your issue. Please update your container and let me know what happens. 

ALSO if you can set this ENV var `LOG_LEVEL=debug` or change it from the status page by clicking **debug**

**Comment by crosbyh** [comment]
I downloaded the latest update on `develop` and it solved the problem. Multi-scrobbler and Maloja seem fully functional. Thanks for the help and for developing multi-scrobbler! Very excited to have this set up.
