### ISSUE TITLE
Trouble initializing last.fm connection

### ISSUE THREAD

**Issue by rmarchant** [FoxxMD/multi-scrobbler#60]
Hello,

I have the following output when launching multi-scrobbler:

```
2023-01-09T19:10:08-08:00 info   : [Scrobblers] (myLastFm) lastfm client initialized
2023-01-09T19:10:08-08:00 info   : [API - Lastfm - myLastFm] No session key found. User interaction for authentication required.
2023-01-09T19:10:08-08:00 warn   : [Scrobblers             ] (myLastFm) lastfm client auth failed.
2023-01-09T19:10:08-08:00 warn   : [Source - Jellyfin - jellyfin] Initializing, but with no filters! All tracks from all users on all servers will be scrobbled.
2023-01-09T19:10:08-08:00 info   : [Sources                                ] (jellyfin) jellyfin source initialized
2023-01-09T19:10:08-08:00 info   : [App                                    ] Server started at http://localhost:9078
2023-01-09T19:10:39-08:00 info   : [Source - Jellyfin - jellyfin] New Track => Jo's Moving Day - Summer Storm @ 2023-01-09T19:10:09-08:00
2023-01-09T19:10:39-08:00 warn   : [Scrobblers                             ] Cannot scrobble to Client 'myLastFm' because user interaction is required for authentication
```

My config is as follows (redacted keys)
```
[
  {
    "name": "myLastFm",
    "configureAs": "client",
    "clients": [],
    "data": {
      "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "callbackUri": "http://10.15.14.5:9078/lastfm/callback"
    }
  }
]
```

When creating the API application on last.fm, I ensured to use `http://10.15.14.5:9078/lastfm/callback` for the callback uri.

Does the callback uri need to be publicly accessible? It is currently only accessible on my local network.

When I navigate to http://10.15.14.5:9078/, I click the link  "(re)authenticate or initialize", then click on "Yes, allow access" on the Last.fm page (the page correctly shows the application name associated with the apikey/secret), but am returned a 404 Page not found error by Last.fm, and the initialization is not completed.

The URL returned in the 404 is (redacted token) : 

`https://www.last.fm/api/undefined?state=myLastFm&token=xxxxxxxxxxxxxxxxxxxxxxxxx`

Any tips? Thanks in advance!

**Comment by rmarchant** [comment]
I changed the lastfm json config callbackuri to use `localhost` rather than local ip, and got past the initial 404 -- instead being redirected to `localhost` (page not found since it's hosted on another machine), i replaced `localhost` in the browser url to my server ip `10.15.14.5`, got an 'OK' response on reload. Restarted the app, and i've never been more authenticated. cheers and thanks for this app

**Comment by FoxxMD** [comment]
Glad you got it figured out!

For anyone seeing this in the future: it's important to understand the callback url is where last.fm tells **your browser on the machine you are on** to visit. It's not a url that needs to be accessibly publicly or accessible by last.fm, etc..only that it needs to be accessible from whatever machine your are currently on. 

And the url should be to the machine where multi-scrobbler is located -- basically whatever hostname you would use to access the MS dashboard is the same hostname you should use for the callback url.

**Comment by rmarchant** [comment]
To clarify a bit more, the issue I ran into, was that Last.fm did not like an IP in the callback url, but rather required a hostname/fqdn.

**Comment by hugalafutro** [comment]
For me, the ip in callback didn't matter for last.fm, I had to get the OK page, leave it open, restart multi-scrobbler, and "it just works"

**Comment by janw** [comment]
For anyone coming here having trouble with initialization in a Kubernetes environment, where the config is stored in a Secret or ConfigMap resource: After the successful callback (OK page), there will be a new file in the pod under `/config/currentCreds-lastfm-<name>.json`. In it you'll find the `sessionKey` that can be added to your actual config.json next to the last.fm API key, as the `session` or via the `LASTFM_SESSION` environment variable to persist it between pod restarts.
