### ISSUE TITLE
Feature: Implement endpoint or push notifications for source health checks

### ISSUE THREAD

**Issue by FoxxMD** [FoxxMD/multi-scrobbler#66]
Based on #65 

[ ] Implement a healthcheck endpoint to monitor status (running/idle) of sources/clients
[ ] Integrate discord webhook or something like pusher webhook to allow notifications when health changes for sources/clients

**Comment by Karsten-Yan** [comment]
The webhook would probably also support REST notification services like gotify or notify.sh, correct? If so, that would be awesome, looking forward to that feature!

**Comment by FoxxMD** [comment]
@iluvatyr @Karsten-Yan 

I've implemented webhooks for Gotify/Ntfy as well as a health check endpoint. Preview in `develop`

Webhooks can be added to `config.json` using `webhooks` property (see [schema](https://json-schema.app/view/%23?url=https%3A%2F%2Fraw.githubusercontent.com%2FFoxxMD%2Fmulti-scrobbler%2Fdevelop%2Fsrc%2Fcommon%2Fschema%2Faio.json) for examples and structure)

```json
{
  "sources": [
  ],
  "clients": [],
  "webhooks": [
    {
      "type": "gotify",
      "url": "..."
    }
  ],
}
```

Health endpoint can be accessed at `http://YourMsURL/health`

* returns `200` when everything is working or `500` if anything is not
* the plain url (`/health`) aggregates status of all clients/sources -- so _any_ failing client/source will make status return `500`
* use query params `type` or `name` to restrict client/sources aggregated IE `/health?type=spotify` or `/health?name=MyMaloja`
* on `500` response returns a JSON payload with "messages" that describes the issue
  * for any clients/sources that require authentication /health will return 500 if they are not authenticated
  * for sources that poll (spotify, yt music, subsonic) /health will 500 if they are not polling

**Comment by iluvatyr** [comment]
This is one of the best things! Thanks for this. I only suggest adding something to send a testmessage to test if the message is coming correctly, either by pressing "Ping gotify/ntfy" in webui, or via terminal `docker exec -it multi-scrobbler pushgotify`

**Comment by FoxxMD** [comment]
> adding something to send a testmessage 

I'll think about it...you can already verify your notification servers are at least reachable by checking the logs at startup. MS attempts to contact the servers on known version/health endpoints and will log an error or success based on that.

```
2023-02-28T12:43:23-05:00 verbose: [Gotify - Config 0] Initialized. Found Server version 2.2.4
2023-02-28T12:43:23-05:00 info   : [Ntfy - Config 1  ] Initialized. Found Ntfy server
```
```
2023-02-28T12:45:29-05:00 error  : [Gotify - Config 0] Failed to contact server | Error: connect ECONNREFUSED 192.168.0.100:8076
2023-02-28T12:45:32-05:00 error  : [Ntfy - Config 1  ] Failed to contact Ntfy server | Error: connect EHOSTUNREACH 192.168.0.100:9991
```

Will also think on filtering notification types.
