### ISSUE TITLE
`ENOENT: no such file or directory, open 'undefined/currentCreds-lastfm-lastfm-XXXX.json'`

### ISSUE THREAD

**Issue by samdoshi** [FoxxMD/multi-scrobbler#71]
[Please check the FAQ](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/FAQ.md) before submitting a bug report.

**Describe the bug**

I've upgraded my Docker based installation, and am unable to re-authenticate Last.fm.

I'm receiving the following error on the callback page:

```
ENOENT: no such file or directory, open 'undefined/currentCreds-lastfm-lastfm-XXXX.json'
```

Looks like the config dir isn't propagating correctly.

**Versions (please complete the following information):**

- multi-scrobbler: 0.4.0 on Docker

**Comment by FoxxMD** [comment]
Please check the [v0.4.0 release/migration notes](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.0) and the [updated docker install documentation](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/installation.md#docker).

The docker image defaults to [`CONFIG_DIR=/config`](https://github.com/FoxxMD/multi-scrobbler/blob/master/Dockerfile#L20) but it looks like maybe your container is defining `CONFIG_DIR` with an empty value (`CONFIG_DIR=` ?) Can you provide the `docker run` command used to start the container?

**Comment by samdoshi** [comment]
I'm on NixOS, and running it with Podman via a SystemD service, but this is the `ExecStart`:

```bash
exec podman run \
  --rm \
  --name='multi-scrobbler' \
  --log-driver=journald \
  --cidfile=/run/podman-'multi-scrobbler'.ctr-id \
  --cgroups=no-conmon \
  --sdnotify=conmon \
  -d \
  --replace \
  -e 'LOG_LEVEL'='debug' \
  -e 'PGID'='1000' \
  -e 'PUID'='1000' \
  -p '9078:9078' \
  -v '/home/sam/Containers/multi-scrobbler:/config' \
  docker.io/foxxmd/multi-scrobbler:0.4.0
```

But I've just retried it with:

```bash
exec podman run \
  --rm \
  --name='multi-scrobbler' \
  --log-driver=journald \
  --cidfile=/run/podman-'multi-scrobbler'.ctr-id \
  --cgroups=no-conmon \
  --sdnotify=conmon \
  -d \
  --replace \
  -e 'CONFIG_DIR'='/config' \
  -e 'LOG_LEVEL'='debug' \
  -e 'PGID'='1000' \
  -e 'PUID'='1000' \
  -p '9078:9078' \
  -v '/home/sam/Containers/multi-scrobbler:/config' \
  docker.io/foxxmd/multi-scrobbler:0.4.0
```

And it still has the same issue

**Comment by FoxxMD** [comment]
@samdoshi can you try `docker.io/foxxmd/multi-scrobbler:develop` and see if that fixes your issue?

**Comment by samdoshi** [comment]
Just tried it now, it has fixed my issue. I got an `OK` on the callback page. And the `currentCreds-lastfm-lastfm-XXXX.json` file was created.

Thank you so much for the quick response.

(I did have to restart the container after authenticating for it to pick up the authentication though)
