### ISSUE TITLE
Tautulli scrobbling not working after update

### ISSUE THREAD

**Issue by rumpff** [FoxxMD/multi-scrobbler#77]
I updated multiscrobbler and tautulli to the newest versions but now i get the following error in the ms console whenever a track is listened

> TypeError: Cannot destructure property 'artist_name' of 'obj.body' as it is undefined.
>     at Function.formatPlayObj (C:\Users\Administrator\Documents\multi-scrobbler\src\sources\TautulliSource.js:16:17)
>     at C:\Users\Administrator\Documents\multi-scrobbler\src\index.js:210:57
>     at wrappedMiddleware (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\@awaitjs\express\index.js:116:13)
>     at Layer.handle [as handle_request] (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\layer.js:95:5)
>     at next (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\route.js:144:13)
>     at Route.dispatch (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\route.js:114:3)
>     at Layer.handle [as handle_request] (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\layer.js:95:5)
>     at C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\index.js:284:15
>     at Function.process_params (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\index.js:346:12)
>     at next (C:\Users\Administrator\Documents\multi-scrobbler\node_modules\express\lib\router\index.js:280:10)

and this error in tautulli

> Tautulli NotificationHandler :: Notification thread exception: decoding str is not supported
> Traceback (most recent call last):
>     File "plexpy\request.py", line 178, in request_response2
>     File "requests\models.py", line 1021, in raise_for_status
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9078/tautulli
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>     File "plexpy\notification_handler.py", line 78, in process_queue
>     File "plexpy\notification_handler.py", line 430, in notify
>     File "plexpy\notifiers.py", line 713, in send_notification
>     File "plexpy\notifiers.py", line 970, in notify
>     File "plexpy\notifiers.py", line 4228, in agent_notify
>     File "plexpy\notifiers.py", line 977, in make_request
>     File "plexpy\request.py", line 207, in request_response2
>     File "plexpy\request.py", line 318, in server_message
> TypeError: decoding str is not supported 

I updated the webhook JSON data to what's listed in the docs currently
running on windows server 2019 version 1809

i have a tautulli users with username and email, both don't work

**Comment by FoxxMD** [comment]
I've added a fix to the `develop` branch, please update and let me know if that fixes the issue for you.

**Comment by rumpff** [comment]
hasn't fixed it, getting the same errors

**Comment by FoxxMD** [comment]
Can you confirm that you checked out the develop branch and pulled the latest changes? What is the output of `git rev-parse HEAD` when run from the project directory?

**Comment by rumpff** [comment]
> Can you confirm that you checked out the develop branch and pulled the latest changes? What is the output of this command when run from the project directory?
> 
> ```
> git rev-parse HEAD
> ```

c10d46b77435402dc284b574836b1713c9a5fc2d

**Comment by FoxxMD** [comment]
What version of Tautulli are you running? It's on the settings -> Help & Info tab.

**Comment by rumpff** [comment]
Version v2.12.3

**Comment by FoxxMD** [comment]
After updating the branch did you rebuild the project with `npm run build` or `tsc -p .` ?

I've added additional checks to develop if you want to try updating. 

Your initial bug report was reproducible but the first commit should have fixed it, the [`TautulliSource.formatPlayObj` method](https://github.com/FoxxMD/multi-scrobbler/commit/c10d46b77435402dc284b574836b1713c9a5fc2d) is only used in two places so the bug's scope was pretty small. I'm trying to remove any assumptions about why it's still occurring for you before digging any deeper (there isn't much deeper to dig).

**Comment by FoxxMD** [comment]
Any update @rumpff ?

**Comment by FoxxMD** [comment]
If you would like to revist this i can re-open.
