### ISSUE TITLE
Kodi url transform not working

### ISSUE THREAD

**Issue by hugalafutro** [FoxxMD/multi-scrobbler#79]
[Please check the FAQ](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/FAQ.md) before submitting a bug report.

**Describe the bug**
Whatever value I put into KODI_URL or in the kodi.json MS mangles it to default http://localhost:8080/jsonrpc I have confirmed the url I'm putting it works (when I put it into browser and put in my name and pass it spits out the json)

**To Reproduce**
1. set the url either via env or json
2. restart MS
3. ???

**Expected behavior**
should authenticate to kodi

**Logs**
`2023-05-25T14:18:18+01:00 debug : [Sources] [Kodi - Kodi] Config URL: '192.168.1.129' => Normalized: 'http://localhost:8080/jsonrpc'`

`2023-05-25T14:19:49+01:00 debug : [Sources] [Kodi - Kodi] Config URL: 'http://192.168.1.129' => Normalized: 'http://localhost:8080/jsonrpc'`

`2023-05-25T14:08:19+01:00 debug : [Sources] [Kodi - Kodi] Config URL: '192.168.1.129:8080' => Normalized: 'http://localhost:8080/jsonrpc'`

`2023-05-25T14:22:13+01:00 debug : [Sources] [Kodi - Kodi] Config URL: '192.168.1.129:8080/jsonrpc' => Normalized: 'http://localhost:8080/jsonrpc'`

`2023-05-25T14:12:52+01:00 debug : [Sources] [Kodi - Kodi] Config URL: 'http://192.168.1.129:8080' => Normalized: 'http://localhost:8080/jsonrpc'`

`2023-05-25T14:15:18+01:00 debug : [Sources] [Kodi - Kodi] Config URL: 'http://192.168.1.129:8080/jsonrpc' => Normalized: 'http://localhost:8080/jsonrpc'`

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: foxxmd/multi-scrobbler:latest in docker
- Kodi 20.1

**Additional context**
Kodi is last thing I need to connect to MS, please help, thanks!

**Comment by FoxxMD** [comment]
It would help if I hadn't hardcoded `'http://localhost:8080/jsonrpc'` as the URL to use, oops :sweat_smile:  was probably left over when i was developing/debugging and didn't revert it. Try the `develop` branch/image and see if that fixes it.

**Comment by FoxxMD** [comment]
I'll mention you when i release to master

**Comment by FoxxMD** [comment]
@hugalafutro this is available on the `latest` docker image and `master` branch now.
