### ISSUE TITLE
[Notifiers] Getting 403 errors on self-hosted ntfy server

### ISSUE THREAD

**Issue by thelazyoxymoron** [FoxxMD/multi-scrobbler#80]
I was trying to setup the ntfy based notifier but keep getting the following error despite giving all the parameters correctly.

`[Notifiers] [Ntfy - ntfy] Failed to push notification: Request failed with status code 403`

I've been able to send notifications using curl on the same protected topics on the self-hosted ntfy instance. Don't see any incoming request in the ntfy logs as well. I'm sure I'm doing something silly here, so would appreciate any pointers on debugging this.

webhook config:

```
"webhooks": [
    {
      "name": "ntfy",
      "topic": "Random",
      "type": "ntfy",
      "url": "https://subdomain.domain.com",
      "username": "secretUser",
      "password": "secret_password"
    }
  
```

**Comment by FoxxMD** [comment]
Hi, can you try the `develop` branch or image `foxxmd/multi-scrobbler:develop` and see if that has fixed the auth issue?

**Comment by FoxxMD** [comment]
@thelazyoxymoron can you confirm this fixes things for you? I was able to reproduce and the fix in `develop` should do the trick.

**Comment by thelazyoxymoron** [comment]
Will check tonight and update here.

**Comment by thelazyoxymoron** [comment]
Confirming that the fix works!

**Comment by FoxxMD** [comment]
In release [0.4.6](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.4.6)
