### ISSUE TITLE
Youtube Music Scrobbler crashes

### ISSUE THREAD

**Issue by Nikey646** [FoxxMD/multi-scrobbler#86]
**Describe the bug**
Youtube Music Scrobbler crashes due to error in internal library. Error stack is for output build, so reporting here instead of downstream.

**To Reproduce**
Unknown, happens over time.

**Expected behavior**
Youtube Music Scrobbler not freezing while being left alone.

**Logs**

```
2023-07-11T00:46:23+10:00 warn : [Sources] [Ytmusic - MyYTMusic] Poll retries (5) equal to max poll retries (5), stopping polling!
2023-07-11T00:46:23+10:00 error : [Sources] [Ytmusic - MyYTMusic] Cannot read properties of undefined (reading 'contents')
TypeError: at o. (/app/node_modules/youtube-music-ts-api/build/exports.js:2:13471) at Generator.next () at a (/app/node_modules/youtube-music-ts-api/build/exports.js:2:10853) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-11T00:46:23+10:00 error : [Sources] [Ytmusic - MyYTMusic] Error occurred while polling
2023-07-11T00:46:21+10:00 debug : [Sources] [Ytmusic - MyYTMusic] Refreshing recently played
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: Latest Docker (foxxmd/multi-scrobbler:latest)

**Comment by FoxxMD** [comment]
Hi. I got a fix for this in the upstream library several weeks ago that handles fetching from YT music but the author seems inactive at the moment. I've updated MS to use my fork for now while waiting for that upstream fix.

Please try using `foxxmd/multi-scrobbler:develop` docker image and let me know if that resolves your issue, thanks.

**Comment by FoxxMD** [comment]
Hi @Nikey646 the latest release includes these fixes as well. You can use `foxxmd/multi-scrobbler:latest` now. Please let me know if this has fixed your issue.

**Comment by FoxxMD** [comment]
Hi @Nikey646 any updates?
