### ISSUE TITLE
Random intermittent bad gateway when scrobbling with Spotify

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#93]
**Describe the bug**
This is the first time I've seen this. Spotify scrobbling was working and then there was a bad gateway error, then scrobbling continued, then there was another bad gateway error. After a while it was constant bad gateway errors one after another and no scrobbling happened. After restarting multi-scrobbler everything was working fine again.

**To Reproduce**
1. Leave multi-scrobbler running
2. Error sometimes happens
3. Error sometimes stops
4. Scrobbles sometimes happen
5. Error sometimes starts

**Expected behavior**
Constant uninterrupted Spotify scrobble

**Logs**
```
[Sources] [Spotify - unnamed] Refreshing recently played
[Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
 [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
 [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
ErrorWithCause:
    at SpotifySource.callApi (CWD/src/sources/SpotifySource.js:195:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SpotifySource.getCurrentPlaybackState (CWD/src/sources/SpotifySource.js:139:29)
    at async SpotifySource.getRecentlyPlayed (CWD/src/sources/SpotifySource.js:101:31)
    at async AbstractSource.doPolling (CWD/src/sources/AbstractSource.js:151:38)
    at async AbstractSource.startPolling (CWD/src/sources/AbstractSource.js:113:21)
    at async SpotifySource.poll (CWD/src/sources/SpotifySource.js:218:13)

caused by: WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Bad gateway..
    at _toError (CWD/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at CWD/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (CWD/node_modules/superagent/lib/node/index.js:867:3)
    at CWD/node_modules/superagent/lib/node/index.js:1070:18
    at IncomingMessage.<anonymous> (CWD/node_modules/superagent/lib/node/parsers/json.js:21:7)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (CWD/node_modules/superagent/lib/node/unzip.js:54:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
...
: [Sources] [Spotify - unnamed] Poll retries (2) less than max poll retries (5), restarting polling after 15 second delay...
: [Sources] [Spotify - unnamed] Polling started
 [Sources] [Spotify - unnamed] Refreshing recently played
 : [Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
: [Sources] [Spotify - unnamed] [Platform xx] New plays found that do not match existing candidates.
: [Sources] [Spotify - unnamed] [Platform xx] Adding new locked play: (xx) xx - xx
 : [Sources] [Spotify - unnamed] [Platform xx] Existing candidate not found in locked plays will be removed: (xx)
 : [Sources] [Spotify - unnamed] No new tracks discovered
 : [Sources] [Spotify - unnamed] Last activity was at 2023-09-01T18:49:56+00:00. Will sleep for interval 30 seconds.
: [Sources] [Spotify - unnamed] Sleeping for 30s
: [Sources] [Spotify - unnamed] Refreshing recently played
: [Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
: [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
 [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
ErrorWithCause:
    at SpotifySource.callApi (CWD/src/sources/SpotifySource.js:195:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
...error repeats more times
[Sources] [Spotify - unnamed] Poll retries (5) equal to max poll retries (5), stopping polling!
```

**Versions (please complete the following information):**
- multi-scrobbler: 0.4.4 flatpak
- maloja `next_minor_version` branch combined with the Spotify extended listening history fix: https://github.com/duckfromdiscord/maloja/tree/import_fix

**Additional context**
It basically switched between bad gateway and normal scrobbling, then went to only bad gateway until restarted, at that time backlog worked properly with no double scrobbles and everything returned to normal. Have not yet seen it happen again since this restart.

**Comment by FoxxMD** [comment]
I also had this issue on friday! Given that, I think this is squarely on spotify's end and not an issue with MS

**Comment by duckfromdiscord** [comment]
Ok this must be a spotify issue 🙂

**Comment by FoxxMD** [comment]
@duckfromdiscord  I've added a monitoring feature that will check polling sources (like spotify) every 20 minutes and attempt to restart them automatically if they are not polling due to upstream issues. It's available in `develop` branch and docker image right now.

**Comment by duckfromdiscord** [comment]
Awesome! I'll have to figure out how to migrate out of flatpak whilst keeping my settings

**Comment by FoxxMD** [comment]
> how to migrate out of flatpak

The settings/data for MS are all contained within one folder, regardless of installation method.

For flatpak this folder should be 

```
/home/YOURUSER/.var/app/io.github.foxxmd.multiscrobbler/config
```


You could technically keep using this folder but for visibility I would copy it elsewhere, say `/home/YOURUSER/msConfig`. Then to use with docker just [mount that same folder into the container](https://foxxmd.github.io/multi-scrobbler/docs/installation#storage) like this

```
docker run -v /home/YOURUSER/msConfig:/config foxxmd/multi-scrobbler
```

If you are using environmental variables with flatpak like `flatpak run --env=SPOTIFY_CLIENT_ID=yourId ...` these convert like this to docker `docker run -e "SPOTIFY_CLIENT_ID=yourId" ...`

When running docker make sure you [map the container port](https://foxxmd.github.io/multi-scrobbler/docs/installation#networking) and if you are using linux set [PGID and PUID](https://foxxmd.github.io/multi-scrobbler/docs/installation#linux-host). Docker examples with a "full" command [here.](https://foxxmd.github.io/multi-scrobbler/docs/installation#docker-usage-examples)
