### ISSUE TITLE
Random scrobble stopping on spotify

### ISSUE THREAD

**Issue by duckfromdiscord** [FoxxMD/multi-scrobbler#99]
**Describe the bug**
This is my first time having this issue. Multi-scrobbler was working just fine with spotify until it randomly stopped working. There is nothing important outside of the logs sent, everything was working fine and there is no context.

**To Reproduce**
1. Leave multi-scrobbler on
2. Random issue

**Logs**

```
[Sources] [Spotify - unnamed] Request failed but retries (0) less than max (1), retrying request after 2 seconds...
 error   : [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
error   : [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
 error   : [Sources] [Spotify - unnamed] Request failed on retry (1) with no more retries permitted (max 1)
ErrorWithCause:
    at SpotifySource.callApi (CWD/src/sources/SpotifySource.js:195:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SpotifySource.getCurrentPlaybackState (CWD/src/sources/SpotifySource.js:139:29)
    at async SpotifySource.getRecentlyPlayed (CWD/src/sources/SpotifySource.js:101:31)
    at async AbstractSource.doPolling (CWD/src/sources/AbstractSource.js:151:38)
    at async AbstractSource.startPolling (CWD/src/sources/AbstractSource.js:113:21)
    at async SpotifySource.poll (CWD/src/sources/SpotifySource.js:218:13)

caused by: WebapiError: [object Object]
    at _toError (CWD/node_modules/spotify-web-api-node/src/http-manager.js:47:10)
    at CWD/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (CWD/node_modules/superagent/lib/node/index.js:867:3)
    at IncomingMessage.<anonymous> (CWD/node_modules/superagent/lib/node/index.js:1070:18)
    at Stream.emit (node:events:513:28)
    at Unzip.<anonymous> (CWD/node_modules/superagent/lib/node/unzip.js:54:12)
    at Unzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
warn    : [Sources] [Spotify - unnamed] Poll retries (5) equal to max poll retries (5), stopping polling!

```

**Versions (please complete the following information):**
- multi-scrobbler: 0.4.4 flatpak
- maloja `next_minor_version` branch combined with the Spotify extended listening history fix: https://github.com/duckfromdiscord/maloja/tree/import_fix

**Additional context**
Random issue, no suspicious surrounding messages, no context

**Comment by FoxxMD** [comment]
Other than the root error not displaying correctly -- it should be a message rather than `[object Object]` -- there's nothing that can really be done about this. This is an upstream issue, MS having trouble communicating with spotify's api. I also had some polling restarts for spotify yesterday.

You can update your flatpak version to [0.5.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.5.2) which includes an automatic polling restart check every 20 minutes. It won't fix spotify having server trouble but it'll save you having to restart polling manually.

**Comment by duckfromdiscord** [comment]
I ran `flatpak update` but I was updated to 0.5.0 "Bump release to 0.5.0 (36722220)"

**Comment by FoxxMD** [comment]
I've merged two updates [[1]](https://github.com/flathub/io.github.foxxmd.multiscrobbler/pull/5) [[2]](https://github.com/flathub/io.github.foxxmd.multiscrobbler/pull/6#event-10438503809) to the flathub but they have yet to update the remote package. I'll try to figure out why its not updating..

**Comment by duckfromdiscord** [comment]
Ok just had the issue in OP again 😅

**Comment by duckfromdiscord** [comment]
Let me know when 0.5.2 is out

**Comment by FoxxMD** [comment]
@duckfromdiscord  I had the same communication issues yesterday. 0.5.2 is [available on flathub](https://flathub.org/apps/details/io.github.foxxmd.multiscrobbler) now.

**Comment by duckfromdiscord** [comment]
@FoxxMD I observed in my logs that polling stopped for about two minutes, then it said "Should be polling!" and scrobbled backlog from way before it paused. Is it possible to only scrobble backlog that started within a certain amount of time of the beginning of the error?

**Comment by duckfromdiscord** [comment]
For some reason I keep getting double scrobbles with times about 5 minutes after the original scrobbles. They seem to always be after the original scrobble but before the next scrobble. Perhaps this is within the scope of #91

**Comment by wynkenstein** [comment]
Same problem for me. On FreeBSD, scrobble from spotify and save to Maloja. As long as the scrobbler is running, everything seems fine, but after restarting Multiscrobbler it reads a bunch of backlog songs which are already scrobbled and scrobbles them again with exactly 3 minutes of time difference. Sometimes it affects 5 songs, sometimes 20, it depends on the backlog size.
